Public Template Repository:: A publicly accessible repository of Service Templates, formatted in a standardized manner, intended to facilitate sharing, discovery, and reuse of service configurations. (Read more: <<repository-and-integrity>>).


== General considerations
[[onboarding-considerations]]

=== Onboarding

This specification is an open standard that describes the protocol, messages and formats used to enable Domain Connect between a Service Provider and a DNS Provider. 

Any Service Provider is free to define and publish a template. However, the terms and conditions for a DNS Provider onboarding a Service Provider template is beyond the scope of this document. A DNS Provider can be selective in what templates they support, can require a contractual relationship, or even charge a fee for onboarding. 

One way a Service Provider can be selective in which DNS Providers they accept is to implement a whitelist of `providerIds`. A Service Provider who chooses to whitelist MUST use `providerId` to distinguish between unique DNS Providers. The DNS Provider's `providerId` would typically be a domain name.

=== Public Template Repository
==== General information
The Public Template Repository is an open accessible location where Service Providers
MAY publish their Service Templates in the format specified in this specification.
DNS Providers MAY support all of the published templates, just a subset or none of them according
to own onboarding policies (see also: <<onboarding-considerations>>).

The template format is intended largely for documentation and communication between the DNS Providers and
Service Providers, and there are no codified endpoints for creation or modification of these objects.
Instead, Domain Connect references a template by ID.

As such, DNS Providers may or may not use templates in this format in their internal implementations. By defining a standard template format, it is believed it will make it easier for Service Providers to share their configuration across DNS Providers.

==== Repository Location
The  repository of the templates is maintained under
https://github.com/Domain-Connect/templates.

[[repository-file-names-requirements]]
==== File naming requirements
The file names in this repository MUST be all lower case, including the `providerId` and `serviceId`. As a result, while the `providerId` and `serviceId can be mixed case, all `providerIds` and `serviceIds` in this repository MUST be unique when lower case.

Templates MUST be named according the following pattern: `{providerId}.{serviceId}.json`

.A non-normative example of file-name inte template repository
[source]
----
providerId: example.com
serviceId: WebsiteBuilder

Template file name: example.com.websitebuilder.json
----

[[repository-and-integrity]]
==== Template Integrity
Implementers are responsible for data integrity and MUST use the record type field to validate that variable input meets the criteria for each different data type.

Hard-coded host names are the responsibility of the DNS Provider to protect. That is, DNS Providers MUST ensure that host names do not interfere with known values (such as `m.` or `www.` or `mail.`) or internal names that provide critical functionality that is outside the scope of this specification.

=== Template Versioning

If a breaking change is made to a template it is recommended that a new template be created. While on the surface versioning looks appealing, in reality this is rarely needed.

Any changes to the template need to account for existing users with settings in DNS, some applied through Domain Connect and some manual. So when changes are made, they are often backward compatible.

Note that when a template changes, it does need to be on-boarded with the DNS Providers.

The <<template-definition, version field>> of the template definition serves the purpose of transparency between the DNS Provider and the Service Provider in case of such changes.

=== PointsTo in Template

Template records of certain types contain the `pointsTo` value to set in the zone. For record types such as `CNAME` where this can be a fully qualified domain name.

A value of `@` in `pointsTo` field in the template is a shortcut for the fully qualified domain name of the domain/host being applied.

Consider a template record of type `CNAME` with a `pointsTo` value of `"@"`. After a template of `domain=example.com` and an empty host is applied, the `pointsTo` value (or corresponding field) in the resulting zone would be `"example.com"`. After a template of `domain=example.com` with `host=bar` is applied, the points to value would be `"bar.example.com"`.

Any domain in a `pointsTo` field in a template MUST be considered fully qualified and not relative.

=== Host/Name in Template

Template records contain the host name of the record to set into the zone (called name for SRV records). This value MUST be considered relative to the domain/host when the template is applied, unless followed by a trailing ".".

Consider a template record of type A with a host value of "xyz". When the template is applied to a domain=example.com and an empty host value, the resulting zone after the template is applied will contain an A record of "xyz" (or "xyz.example.com." as absolute domain name in DNS master file notation).

If the same template is applied to a domain=example.com and host=bar, the zone will contain an A
record of "xyz.bar" (or "xyz.bar.example.com." as absolute domain name).

A value of @ for host in the template is a placeholder for an empty value. In other words @
would point to "bar.example.com." when the same template is applied to domain=example.com and host=bar.


=== Template Scope

For DNS Providers that maintain template state, an individual template is scoped to the set of records applied to a fully qualified domain. This includes the Zone Apex and the host (aka Sub Domain) at apply time.

As an example, if a template is applied on `domain=example.com&host=sub1` a later application of the template on `domain=example.com&host=sub2` must be treated as a distinct template. If a conflict is detected later with the records set into `"sub2.example.com"`, only the records set with this template would be removed.

== Extensions/Exclusions
=== General information
Additional record types and/or extensions to records in the template can be implemented on a per DNS Provider basis. However, care should be taken when defining extensions so as to not conflict with other protocols and standards. Certain record names are reserved for use in DNS for protocols like DNSSEC (DNSKEY, RRSIG) <<RFC9364>> at the registry level.

Defining these OPTIONAL extensions in an open manner as part of this specification is done to provide consistency. The following are the initial OPTIONAL extensions a DNS Provider/Service Provider may support.

=== APEXCNAME

Some Service Providers desire the behavior of a CNAME record, but in the
apex record. This would allow for an A Record at the root of the domain
but dynamically determined at runtime.

The recommended record type for DNS Providers that wish to support this
is an APEXCNAME record. Additional fields included with this record
would include pointsTo and TTL.

Defining a standard for such functionality in DNS is beyond the scope of
this specification. But for DNS Providers that support this
functionality, using the same record type name across DNS Providers
allows template reuse.

=== Redirection

Some Service Providers desire a redirection service associated with the
A Record. A typical example is a service that requires a redirect of the
domain (e.g. example.com) to the www variant (www.example.com). The www
would often contain a CNAME.

Since implementation of a redirection service is typically simple, it is recommended that Service Providers implement redirection on their own.
But for DNS Providers that have a redirection service, supporting simple templates with this functionality may be desired.

While technically not a "record" in DNS, when supporting this OPTIONAL functionality it is recommended that this SHOULD be implemented using two new record types.

REDIR301 and REDIR302 would implement 301 and 302 redirects respectively. Associated with this record would be a single field called the "target", containing the target url of the redirect.

Please note, that setting up an HTTP redirect typically involves setting up a webserver and configuring A and AAAA records pointing to this webserver accordingly. The template may or may not explicitly define those records, as the orchestration and the values would we controlled by the DNS provider, not the Service Provider. The DNS Provider SHOULD however consider those records during the conflict resolution in order to give transparency of the changes to the user.

=== Nameservers

Several Service Providers have asked for functionality supporting an update to the nameserver records at the registry associated with the domain.

When implementing this functionality a template defined at DNS Provider would need to define a set of NS records, typically a minimum of 2 and a maximum depending on the number supported by the registrar system of the DNS Provider, likely with `groupIds` to allow for optionality of those additional nameservers. Each NS entry would then contain a `data` field with desired host names or variables to allow for dynamic setup.

It will be noted that a nameserver update would require that the entity implementing DNS Provider side of the protocol is the Registrar. This is not always the case.

Additional care would have to be taken by the DNS Provider informing the user about the change happening and the impact of the change.

This functionality is again deemed as OPTIONAL and up to the DNS Provider to determine if they will support this.

=== DS (DNSSEC)

Requests have been made to allow for updates to the DS record for
DNSSEC. This record is required at the registry to enable DNSSEC, but can only be written by the registrar.

For DNS Providers that support this record, the record type would be DS. Values will be keyTag, algorithm, digestType, and digest.

Again it should be noted that a DS update would require that the entity implementing DNS Provider side of the protocol is the registrar, and is again deemed as OPTIONAL and up to the DNS Provider to determine if they will support.

[[spf-record-merging]]
=== SPF TXT Record
==== What is SPF?

SPF stands for Sender Policy Framework specified in
<<RFC7208>>. It is a
record that specifies a list of authorized host names and/or IP addresses from which mail
can originate from for a given domain name.

It manifests itself as a TXT record.  The format of which starts with v=spf1 followed by a list of “rules” of
what to include/exclude.  If a rule passes, the mail is allowed. If it fails, it moves to the next rule.
Typical record might appear as:

----
v=spf1 include:policy.exampleprovider.example -all
----

This is an SPF record with two rules.  The first rule indicates that the rules for SPF record
`_policy.exampleprovider.example` be included in this record. The second rule is a catch all (`all`). The default modifier for a rule is `pass` (+). Other modifiers are `hard failure` (`-`), `soft failure` (`~`) and `neutral` (`?`).

Note: A failure in SPF doesn't mean delivery won't happen, however depending on the policies of the receiving system, messages classified with `hard failure` or `soft failure` may not be delivered or marked as spam.

The use of “all” at the end  is pretty common, although some providers mark it as `~` (soft fail) or `?` (neutral). The reality is that a good SPF record is tuned based on what services are attached to a domain. Not just one individual service.

[[multiple-services]]
==== Multiple Services

If only one email sending service were active, the SPF record recommended by the provider is sufficient. But
mail from a domain can often come from several different services.

A very typical use case might be end user mail and an email newsletter service.
Let’s look at the SPF records recommended for individual services.

Mailer1: v=spf1 include:spf.mailer1.example –all
Newsletter1: v=spf1 include:_spf.newsletter.example ~all

All of these examples use the include syntax. This is fairly common. The use of all at the end is common,
although is often inconsistent with the modifier.

If a user installed Mailer1 and Newsletter1, their combined SPF record ought to be something like:

----
v=spf1 include:spf.mailer1.example include:_spf.newsletter.example
 ~all
----

We combined the two rules, and in this case picked the least restrictive all modifier.


==== Alternatives

Some DNS Providers MAY decide not to support the SPFM record. The following alternative solution would allow general interoperability of the templates for those providers: onboard the templates with SPFM record in variable-compatible form using a regular TXT record with content `“v=spf1 %spfRules% ~all”`, using property `essential=OnApply` set to avoid removal of the whole template by a conflict.
